### ISSUE TITLE
Test broken?

### ISSUE THREAD

**Issue by unsubtleguy** [stackb/rules_hugo#12]
Hey stackb,

When trying to build the test - I get an error `failed to get relative path: couldn't find content in _index.md` (below).

I haven't done anything to the folder - this is just cloned straight from head.

I might be missing something really obvious - could you point me in the right direction?

```
/tmp/lol/rules_hugo/test/basic on master
$ bazel build :basic 
ERROR: /tmp/lol/rules_hugo/test/basic/BUILD.bazel:17:1: in hugo_site rule //:basic: 
Traceback (most recent call last):
	File "/tmp/lol/rules_hugo/test/basic/BUILD.bazel", line 17
		hugo_site(name = 'basic')
	File "/home/mayhem/.cache/bazel/_bazel_mayhem/cd7a331c55c033d3774e7697c3b55154/external/build_stack_rules_hugo/hugo/internal/hugo_site.bzl", line 50, in _hugo_site_impl
		copy_to_dir(ctx, ctx.files.content, "content")
	File "/home/mayhem/.cache/bazel/_bazel_mayhem/cd7a331c55c033d3774e7697c3b55154/external/build_stack_rules_hugo/hugo/internal/hugo_site.bzl", line 22, in copy_to_dir
		ctx.actions.declare_file(relative_path(i, dirname))
	File "/home/mayhem/.cache/bazel/_bazel_mayhem/cd7a331c55c033d3774e7697c3b55154/external/build_stack_rules_hugo/hugo/internal/hugo_site.bzl", line 22, in ctx.actions.declare_file
		relative_path(i, dirname)
	File "/home/mayhem/.cache/bazel/_bazel_mayhem/cd7a331c55c033d3774e7697c3b55154/external/build_stack_rules_hugo/hugo/internal/hugo_site.bzl", line 16, in relative_path
		fail(("failed to get relative path: c...)))
failed to get relative path: couldn't find content in _index.md
ERROR: Analysis of target '//:basic' failed; build aborted: Analysis of target '//:basic' failed; build aborted
INFO: Elapsed time: 0.057s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

```

**Comment by unsubtleguy** [comment]
Hold up - Looked closer - it looks like it's just depending on blog posts being under the `content/` folder, which would mean one would include files in the BUILD as 'content/blah.md'
